### criar instituição
POST http://localhost:3000/instituicoes
Content-Type: application/json

{
  "nome": "Banco Central",
  "codigo": "001"
}

### buscar instituição por id
GET http://localhost:3000/instituicoes/id-exemplo
Content-Type: application/json

### listar todas as instituições
GET http://localhost:3000/instituicoes
Content-Type: application/json

### atualizar instituição
PUT http://localhost:3000/instituicoes/id-exemplo
Content-Type: application/json

{
  "nome": "Novo Nome do Banco"
}

### deletar instituição
DELETE http://localhost:3000/instituicoes/id-exemplo
Content-Type: application/json