### create user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Test User",
  "cpf": "55555555555"
}

### find user by id
GET http://localhost:3333/users/id/:userId
Content-Type: application/json

### find user by cpf
GET http://localhost:3333/users/cpf/:userCpf
Content-Type: application/json


### find all users
GET http://localhost:3333/users
Content-Type: application/json

### update user
PUT http://localhost:3333/users/:userId
Content-Type: application/json

{
  "cpf": "66666666666",
  "name": "Updated Name"
}

### delete user
DELETE http://localhost:3333/users/:userId
Content-Type: application/json

# acaba o crud 

### create account by user id
POST http://localhost:3333/users/:userId/accounts
Content-Type: application/json
{
  "institution_id": ":institutionId",
  "balance": 2,
  "credit_limit": "1000.00",
  "credit_available": "500.00"
}

### find balances by user id
GET http://localhost:3333/users/:userId/balances
Content-Type: application/json

### find total balance by user id
GET http://localhost:3333/users/:userId/balance/total
Content-Type: application/json

### find balance by institution
GET http://localhost:3333/users/:userId/balance?institution=bras
Content-Type: application/json

### find transactions by user id
GET http://localhost:3333/users/:userId/transactions
Content-Type: application/json

### find transactions by institution
GET http://localhost:3333/users/:userId/transaction?institution=bras
Content-Type: application/json

### debit transaction
POST http://localhost:3333/users/:userId/transactions?institution=bras
Content-Type: application/json

{
  "amount": 62,
  "type": "debit",
  "destination_account_id": ":accountId"
}

### credit transaction
POST http://localhost:3333/users/:userId/transactions?institution=bras
Content-Type: application/json

{
  "amount": 28,
  "type": "credit",
  "destination_account_id": ":accountId"
}