### criar conta
POST http://localhost:3333/contas
Content-Type: application/json

{
  "usuario_id": "fd80f44e-5930-44e6-8d83-9be114e0740a",
  "instituicao_id": "d9fffd99-1abc-445f-f3d4-5ff9bd380a20",
  "saldo": 1000,
  "credito_limite": 100,
  "credito_disponivel": 90
}

### buscar conta por id
GET http://localhost:3333/contas/87c9198c-a33e-44a5-a189-1953d7cf0107
Content-Type: application/json

### buscar conta por usuario_id
GET http://localhost:3333/contas/fd80f44e-5930-44e6-8d83-9be114e0740a/usuarios
Content-Type: application/json

### listar todas as contas
GET http://localhost:3333/contas
Content-Type: application/json

### atualizar conta
PUT http://localhost:3333/contas/id-exemplo
Content-Type: application/json

{
  "saldo": 1500
}

### deletar conta
DELETE http://localhost:3333/contas/id-exemplo
Content-Type: application/json