### create institution
POST http://localhost:3333/institutions
Content-Type: application/json

{
  "name": "Banco para Testes",
  "code": "666"
}

### find institution by id
GET http://localhost:3333/institutions/id/:institutionId
Content-Type: application/json

### find institution by code
GET http://localhost:3333/institutions/code/:institutionCode
Content-Type: application/json

### find all institutions
GET http://localhost:3333/institutions
Content-Type: application/json

### Update institution
PUT http://localhost:3333/institutions/:institutionId
Content-Type: application/json

{
  "name": "New Bank Name",
  "code": "666"
}

### delete institution
DELETE http://localhost:3333/institutions/:institutionId
Content-Type: application/json