### create account
POST http://localhost:3333/accounts
Content-Type: application/json

{
  "user_id": ":userId",
  "institution_id": ":institutionId",
  "balance": 1000,
  "credit_limit": 100,
  "credit_available": 90
}

### find account by id
GET http://localhost:3333/accounts/id/:accountId
Content-Type: application/json

### find accounts by user
GET http://localhost:3333/accounts/user/:userId
Content-Type: application/json

### find all accounts
GET http://localhost:3333/accounts
Content-Type: application/json

### update account
PUT http://localhost:3333/accounts/:accountId
Content-Type: application/json

{
  "balance": 1500,
  "credit_limit": "1000.00",
  "credit_available": "500.00"
}

### delete account
DELETE http://localhost:3333/accounts/:accountId
Content-Type: application/json