### criar conta
POST http://localhost:3333/contas
Content-Type: application/json

{
  "usuario_id": "usuario_id-exemplo",
  "instituicao_id": "instituicao_id-exemplo",
  "saldo": 1000
}

### buscar conta por id
GET http://localhost:3333/contas/id-exemplo
Content-Type: application/json

### listar todas as contas
GET http://localhost:3333/contas
Content-Type: application/json

### atualizar conta
PUT http://localhost:3333/contas/id-exemplo
Content-Type: application/json

{
  "saldo": 1500
}

### deletar conta
DELETE http://localhost:3333/contas/id-exemplo
Content-Type: application/json