### criar usuário
POST http://localhost:3333/usuarios
Content-Type: application/json

{
  "nome": "Fulano de Tal",
  "cpf": "12345678900"
}

### buscar usuário por id
GET http://localhost:3333/usuarios/id-exemplo
Content-Type: application/json

### listar todos os usuários
GET http://localhost:3333/usuarios
Content-Type: application/json

### atualizar usuário
PUT http://localhost:3333/usuarios/id-exemplo
Content-Type: application/json

{
  "nome": "Nome Atualizado"
}

### deletar usuário
DELETE http://localhost:3333/usuarios/id-exemplo
Content-Type: application/json